language: node_js
node_js:
 - "stable"
install: yarn
script: yarn test
cache:
  directories:
    - "node_modules"
branches:
  only:
  - development
before_script:
  - psql -c 'create database teamwork_api;' -U postgres
after_success: yarn coverage
